# Generated by Django 3.1.4 on 2020-12-03 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20201203_1712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('True', 'Yes'), ('False', 'No')], max_length=10, null=True),
        ),
    ]
